export const FETCH_FILTERED_LOTS = 'FETCH_FILTERED_LOTS';
export const SET_FLY_TO_COORDINATES = 'SET_FLY_TO_COORDINATES';
export const SET_LOT_EXPANDED = 'SET_LOT_EXPANDED';
export const SET_SELECTED_TAB = 'SET_SELECTED_TAB';
